### PR TITLE
Enhancements

### LINKED ISSUE #90: UBQ Contributor Airdrop
Make a command line tool that will tally up everybody's contributions from the last year. 

We can parse all the permits generated across all of our repos and then drop 1 UBQ per dollar earned. 

We should run this script when we enable UBQ token payouts

### PR DESCRIPTION
**Pull request by 0x4007**
Resolves https://github.com/ubiquity/.github/issues/90
- Authentication for enhanced rate limits
- Use yarn build
- Enhanced logging

### CODE REVIEW

**Comment by 0x4007** [comment]
I tested with slow internet so I couldn't complete the run in time. Will try again later but so far seems functional with authentication.

image

---

https://github.com/EtherealGlow/ContributionAnalyzer/pull/2/files#diff-12060c1ccac042edab175ad9fa0c53086a60c5d666978c11d00772ae379c2535R46

Alternative link: https://github.com/ubiquity/contribution-analyzer/blob/3f954c01f28a3da4901c53a87697c8e2473f16a4/src/helpers/calculateReward.ts#L46

This approach seems problematic. You should figure out a more robust way to test the comment for links to pay.ubq.fi because I don't believe that every permit has this exact header? Especially the older ones. Study those to confirm. But I assume that every permit since the beginning links to pay.ubq.fi

**Comment by 0x4007** [comment]
You should handle this case. I have to log off my computer now.

```
Organization reward calculated successfully.
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'output/output.csv'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'output/output.csv'
}

Node.js v20.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
m1:ContributionAnalyzer nv$
```

**Comment by EtherealGlow** [comment]
@pavlovcik i found the case that you were talking about
https://github.com/ubiquity/ubiquibot/issues/268#issuecomment-1540101065

to fix this cant i just see first that if the comment contains task creator or conv rewards headers and give the reward to the respective person else it has to be a assignee reward and give it to the assignee

**Comment by EtherealGlow** [comment]
after pushing this commit you can see what i am talking about

**Comment by EtherealGlow** [comment]
@pavlovcik

**Pull request merged**
